logging:
  level:
    "[org.hibernate.stat]": debug

spring:
  devtools:
    add-properties: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": true
      "[persistence.schema-generation.scripts.create-target]": create.sql
