build_prod:
  extends:
    - .create_env
  environment: prod
  stage: build
  only:
    - main
  script:
    - docker compose -f docker-compose.build.yml build --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG

send_image_registry_prod:
  environment: prod
  stage: send_registry
  only:
    - main
  tags:
    - ssh
    - solar-srv1
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $CI_REGISTRY

    - docker compose -f docker-compose.build.yml push

deploy_prod:
  extends:
    - .create_env
  environment: prod
  stage: deploy
  only:
    - main
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $CI_REGISTRY

    - docker stack deploy --with-registry-auth  -c <(docker compose -f docker-compose.deploy.yml config | tail -n +2) ${CI_PROJECT_NAMESPACE}
